@SyncBoard_Api_HostAddress = https://localhost:7059

POST {{SyncBoard_Api_HostAddress}}/api/boards
Content-Type: application/json

{
  "title": "Job Search"
}
###

GET {{SyncBoard_Api_HostAddress}}/api/boards/c6bb5033-d5d7-4dbc-96b1-71e6753e252c

###

GET {{SyncBoard_Api_HostAddress}}/api/boards

###

PATCH {{SyncBoard_Api_HostAddress}}/api/boards/c6bb5033-d5d7-4dbc-96b1-71e6753e252c
Content-Type: application/json

{
  "title": "Career Board"
}
###

DELETE {{SyncBoard_Api_HostAddress}}/api/boards/2418befe-d7a9-479b-99a5-a7211838b24e
###

POST {{SyncBoard_Api_HostAddress}}/api/boards/c6bb5033-d5d7-4dbc-96b1-71e6753e252c/columns
Content-Type: application/json

{
  "title": "Backlog",
  "position": 0
}
###

GET {{SyncBoard_Api_HostAddress}}/api/boards/c6bb5033-d5d7-4dbc-96b1-71e6753e252c/columns
###

PATCH {{SyncBoard_Api_HostAddress}}/api/boards/c6bb5033-d5d7-4dbc-96b1-71e6753e252c/columns/dee6ff57-f58a-4e34-9089-87925ddf3d1e/position
Content-Type: application/json

{
  "position": 2
}