@SyncBoard_Api_HostAddress = https://localhost:7059

POST {{SyncBoard_Api_HostAddress}}/api/boards
Content-Type: application/json

{
  "title": "Job Search"
}

GET http://localhost:5121/api/boards/9155ac15-d42f-4cb9-bca9-8361a946d622